CREATE TABLE IF NOT EXISTS accounts (
	id UUID PRIMARY KEY DEFAULT UUIDV7(),
	email VARCHAR(255) UNIQUE NOT NULL,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	is_email_verified BOOLEAN NOT NULL DEFAULT FALSE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
